### ISSUE TITLE
Unable to start mining or benchmark

### ISSUE THREAD

**Issue by daimaah** [Cryptominer937/zPoolMiner#3]
I ran the version 1.8.1.7 and started benchmarking and after a while, the application crashed silently. After running the application again, I'm unable to benchmark or start mining due to an unhandled exception: 

> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at zPoolMiner.Algorithm.get_CurPayingRatio() in C:\Users\droth\Documents\GitHub\zPoolMiner\zPoolMiner\Algorithm.cs:line 62
   at zPoolMiner.Forms.Components.AlgorithmsListView.SetAlgorithms(ComputeDevice computeDevice, Boolean isEnabled) in C:\Users\droth\Documents\GitHub\zPoolMiner\zPoolMiner\Forms\Components\AlgorithmsListView.cs:line 98
   at zPoolMiner.Forms.Form_Benchmark..ctor(BenchmarkPerformanceType benchmarkPerformanceType, Boolean autostart) in C:\Users\droth\Documents\GitHub\zPoolMiner\zPoolMiner\Forms\Form_Benchmark.cs:line 256
   at zPoolMiner.Form_Main.buttonBenchmark_Click(Object sender, EventArgs e) in C:\Users\droth\Documents\GitHub\zPoolMiner\zPoolMiner\Forms\Form_Main.cs:line 743
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I've tried downloading the package again into a different folder but the same thing keeps happening even with the second installation. I also tried deleting the benchmark file under configs folder, but that didn't help either.

**Comment by Cryptominer937** [comment]
Looking into this now, Most likely has to do with X17 being disabled on zpool due to a bad verge wallet update.

**Comment by Cryptominer937** [comment]
Fixed go to https://github.com/Cryptominer937/zPoolMiner/releases/tag/1.8.1.7
And download the no X17 Version

**Comment by Cryptominer937** [comment]
Re-opening issue to implement a hard code fix for if this issue happens again.

**Comment by Cryptominer937** [comment]
Update: Release after dns propagation 24HRS
Just implemented 3rd party json to fix any future issues if a algo is removed from zpool.ca for any reason. It checks if all options are valid and if one is missing it replaces it and sets profitability to 0 so you switch algos. this json updates every 2 Min to keep zpool api calls low.
