### ISSUE TITLE
Error when clicking Settings > Devices/Algorithms > 'Check all Profitability' button (and check single)

### ISSUE THREAD

**Issue by tsojin** [Cryptominer937/zPoolMiner#4]
T************** Exception Text **************
System.TypeInitializationException: The type initializer for 'zPoolMiner.ProfitabilityCalculator' threw an exception. ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at zPoolMiner.ProfitabilityCalculator..cctor() in C:\Users\droth\Documents\GitHub\zPoolMiner\zPoolMiner\Utils\ProfitabilityCalculator.cs:line 15
   --- End of inner exception stack trace ---
   at zPoolMiner.ProfitabilityCalculator.GetFormatedSpeed(Double speed, AlgorithmType type) in C:\Users\droth\Documents\GitHub\zPoolMiner\zPoolMiner\Utils\ProfitabilityCalculator.cs:line 55
   at zPoolMiner.Forms.Form_Settings.buttonSelectedProfit_Click(Object sender, EventArgs e) in C:\Users\droth\Documents\GitHub\zPoolMiner\zPoolMiner\Forms\Form_Settings.cs:line 698
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Cryptominer937** [comment]
Already have a fix ready for this, It happens when a algo goes offline/Maintenance. I was waiting to know that my new domain was fully ready with a caching API to release but will be out in the next hour.
